apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector: # we keep this selector because it dynamically filter and group objects based on their attached labels.
    project: roboshop
    component: frontend
    environment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port